[package]
name = "ai_model"
version = "0.1.0"
edition = "2021"
description = "Lightweight, high-accuracy machine learning model with text generation, code completion, Q&A, summarization, and visual analysis capabilities"
authors = ["AI Model Team"]
license = "MIT"

[[bin]]
name = "ai_model"
path = "src/main.rs"

[[bin]]
name = "train_tokenizer"
path = "src/bin/train_tokenizer.rs"

[[bin]]
name = "train_model"  
path = "src/bin/train_model.rs"

[lib]
name = "ai_model"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
ndarray = "0.15"
rand = "0.8"
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"
env_logger = "0.10"
uuid = { version = "1.0", features = ["v4"] }
num_cpus = "1.0"
async-trait = "0.1"
# BPE tokenizer dependencies
tokenizers = "0.19"
# Training and dataset utilities  
regex = "1.0"
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "model_performance"
harness = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 1
