name: CI Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.target }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x86_64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: goldbull-linux-amd64
            
          # Linux ARM64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact_name: goldbull-linux-arm64
            
          # Windows x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: goldbull-windows-amd64
            
          # Windows ARM64
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            artifact_name: goldbull-windows-arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install cross-compilation dependencies (Linux ARM64)
      if: matrix.target == 'aarch64-unknown-linux-gnu'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: Set environment variables for aarch64 builds
      if: matrix.target == 'aarch64-unknown-linux-gnu' || matrix.target == 'aarch64-pc-windows-msvc'
      run: |
        echo "RUSTFLAGS=-C target-cpu=generic" >> $GITHUB_ENV
        echo "CARGO_CFG_TARGET_FEATURE=" >> $GITHUB_ENV
        echo "CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
        echo "CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++" >> $GITHUB_ENV
        echo "AR_aarch64_unknown_linux_gnu=aarch64-linux-gnu-ar" >> $GITHUB_ENV
        echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

    - name: Cache cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ matrix.target }}-
          ${{ runner.os }}-cargo-

    - name: Build workspace (check compilation)
      run: cargo check --workspace --target ${{ matrix.target }}

    - name: Build core libraries
      run: |
        cargo build --release --target ${{ matrix.target }} --package goldbull-core
        cargo build --release --target ${{ matrix.target }} --package goldbull-tokenizer

    - name: Build goldbull-brief
      run: cargo build --release --target ${{ matrix.target }} --package goldbull-brief

    - name: Build goldbull-vision
      run: cargo build --release --target ${{ matrix.target }} --package goldbull-vision

    - name: Build goldbull-sage
      run: cargo build --release --target ${{ matrix.target }} --package goldbull-sage

    - name: Build goldbull-embedding
      run: cargo build --release --target ${{ matrix.target }} --package goldbull-embedding

    - name: Build goldbull-multimodel
      run: cargo build --release --target ${{ matrix.target }} --package goldbull-multimodel

    - name: Build goldbull-code
      run: cargo build --release --target ${{ matrix.target }} --package goldbull-code

    - name: Build goldbull-text binary
      run: cargo build --release --target ${{ matrix.target }} --package goldbull-text

    - name: Prepare artifacts directory
      shell: bash
      run: |
        mkdir -p artifacts
        
    - name: Copy binaries (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        # Copy binaries if they exist
        if [ -f "target/${{ matrix.target }}/release/goldbull-text" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-text" artifacts/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-text-train" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-text-train" artifacts/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-code" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-code" artifacts/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-code-train" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-code-train" artifacts/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-sage" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-sage" artifacts/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-sage-train" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-sage-train" artifacts/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-brief" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-brief" artifacts/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-brief-train" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-brief-train" artifacts/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-vision" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-vision" artifacts/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-vision-train" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-vision-train" artifacts/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-multimodel" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-multimodel" artifacts/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-multimodel-train" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-multimodel-train" artifacts/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-embedding" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-embedding" artifacts/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-embedding-train" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-embedding-train" artifacts/
        fi
        
    - name: Copy binaries (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        # Copy binaries if they exist
        if [ -f "target/${{ matrix.target }}/release/goldbull-text.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-text.exe" artifacts/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-text-train.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-text-train.exe" artifacts/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-code.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-code.exe" artifacts/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-code-train.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-code-train.exe" artifacts/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-sage.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-sage.exe" artifacts/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-sage-train.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-sage-train.exe" artifacts/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-brief.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-brief.exe" artifacts/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-brief-train.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-brief-train.exe" artifacts/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-vision.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-vision.exe" artifacts/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-vision-train.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-vision-train.exe" artifacts/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-multimodel.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-multimodel.exe" artifacts/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-multimodel-train.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-multimodel-train.exe" artifacts/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-embedding.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-embedding.exe" artifacts/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-embedding-train.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-embedding-train.exe" artifacts/
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ matrix.artifact_name }}
        path: artifacts/
        retention-days: 30

    - name: Test core libraries
      run: |
        cargo test --target ${{ matrix.target }} --package goldbull-core
        cargo test --target ${{ matrix.target }} --package goldbull-tokenizer

    - name: Test goldbull-brief
      run: cargo test --target ${{ matrix.target }} --package goldbull-brief

    - name: Test goldbull-vision
      run: cargo test --target ${{ matrix.target }} --package goldbull-vision

    - name: Test goldbull-sage
      run: cargo test --target ${{ matrix.target }} --package goldbull-sage

    - name: Test goldbull-embedding
      run: cargo test --target ${{ matrix.target }} --package goldbull-embedding

    - name: Test goldbull-multimodel
      run: cargo test --target ${{ matrix.target }} --package goldbull-multimodel

    - name: Test goldbull-code
      run: cargo test --target ${{ matrix.target }} --package goldbull-code

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}

    - name: Run tests for working packages
      run: |
        cargo test --package goldbull-core
        cargo test --package goldbull-tokenizer

    - name: Run tests for goldbull-text
      run: cargo test --package goldbull-text

    - name: Run tests for goldbull-brief
      run: cargo test --package goldbull-brief

    - name: Run tests for goldbull-vision
      run: cargo test --package goldbull-vision

    - name: Run tests for goldbull-sage
      run: cargo test --package goldbull-sage

    - name: Run tests for goldbull-embedding
      run: cargo test --package goldbull-embedding

    - name: Run tests for goldbull-multimodel
      run: cargo test --package goldbull-multimodel

    - name: Run tests for goldbull-code
      run: cargo test --package goldbull-code

    - name: Run clippy for goldbull-core
      run: cargo clippy --package goldbull-core

    - name: Run clippy for goldbull-tokenizer
      run: cargo clippy --package goldbull-tokenizer

    - name: Run clippy for goldbull-text
      run: cargo clippy --package goldbull-text

    - name: Run clippy for goldbull-brief
      run: cargo clippy --package goldbull-brief

    - name: Run clippy for goldbull-vision
      run: cargo clippy --package goldbull-vision

    - name: Run clippy for goldbull-sage
      run: cargo clippy --package goldbull-sage

    - name: Run clippy for goldbull-embedding
      run: cargo clippy --package goldbull-embedding

    - name: Run clippy for goldbull-multimodel
      run: cargo clippy --package goldbull-multimodel

    - name: Run clippy for goldbull-code
      run: cargo clippy --package goldbull-code

  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Install cargo-audit
      run: cargo install cargo-audit

    - name: Run security audit
      # RUSTSEC-2020-0071 is ignored because it pertains to a vulnerability in a dependency
      # that is either not used in a security-critical context or has been deemed acceptable
      # for our use case after thorough evaluation. See [link to documentation or issue tracker]
      run: cargo audit --ignore RUSTSEC-2020-0071