name: Release Build

on:
  release:
    types: [created]
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release ${{ matrix.target }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x86_64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: goldbull-linux-amd64
            
          # Linux ARM64  
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact_name: goldbull-linux-arm64
            
          # Windows x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: goldbull-windows-amd64
            
          # Windows ARM64
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            artifact_name: goldbull-windows-arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install cross-compilation dependencies (Linux ARM64)
      if: matrix.target == 'aarch64-unknown-linux-gnu'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: Set environment variables for aarch64 builds
      if: matrix.target == 'aarch64-unknown-linux-gnu' || matrix.target == 'aarch64-pc-windows-msvc'
      run: |
        echo "RUSTFLAGS=-C target-cpu=generic" >> $GITHUB_ENV
        echo "CARGO_CFG_TARGET_FEATURE=" >> $GITHUB_ENV
        echo "CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
        echo "CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++" >> $GITHUB_ENV
        echo "AR_aarch64_unknown_linux_gnu=aarch64-linux-gnu-ar" >> $GITHUB_ENV
        echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

    - name: Build core libraries
      run: |
        cargo build --release --target ${{ matrix.target }} --package goldbull-core
        cargo build --release --target ${{ matrix.target }} --package goldbull-tokenizer

    - name: Build goldbull-brief
      run: cargo build --release --target ${{ matrix.target }} --package goldbull-brief

    - name: Build goldbull-vision
      run: cargo build --release --target ${{ matrix.target }} --package goldbull-vision

    - name: Build goldbull-sage
      run: cargo build --release --target ${{ matrix.target }} --package goldbull-sage

    - name: Build goldbull-embedding
      run: cargo build --release --target ${{ matrix.target }} --package goldbull-embedding

    - name: Build goldbull-multimodel
      run: cargo build --release --target ${{ matrix.target }} --package goldbull-multimodel

    - name: Build goldbull-code
      run: cargo build --release --target ${{ matrix.target }} --package goldbull-code

    - name: Build goldbull-text binary
      run: cargo build --release --target ${{ matrix.target }} --package goldbull-text

    - name: Create release directory
      shell: bash
      run: |
        mkdir -p release/${{ matrix.artifact_name }}
        
    - name: Copy binaries and create archive (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        # Copy binaries if they exist
        if [ -f "target/${{ matrix.target }}/release/goldbull-text" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-text" release/${{ matrix.artifact_name }}/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-text-train" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-text-train" release/${{ matrix.artifact_name }}/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-code" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-code" release/${{ matrix.artifact_name }}/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-code-train" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-code-train" release/${{ matrix.artifact_name }}/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-sage" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-sage" release/${{ matrix.artifact_name }}/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-sage-train" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-sage-train" release/${{ matrix.artifact_name }}/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-brief" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-brief" release/${{ matrix.artifact_name }}/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-brief-train" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-brief-train" release/${{ matrix.artifact_name }}/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-vision" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-vision" release/${{ matrix.artifact_name }}/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-vision-train" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-vision-train" release/${{ matrix.artifact_name }}/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-multimodel" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-multimodel" release/${{ matrix.artifact_name }}/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-multimodel-train" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-multimodel-train" release/${{ matrix.artifact_name }}/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-embedding" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-embedding" release/${{ matrix.artifact_name }}/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-embedding-train" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-embedding-train" release/${{ matrix.artifact_name }}/
        fi
        
        # Copy README and LICENSE if they exist
        if [ -f "README.md" ]; then
          cp README.md release/${{ matrix.artifact_name }}/
        fi
        if [ -f "LICENSE" ]; then
          cp LICENSE release/${{ matrix.artifact_name }}/
        fi
        
        # Create tar archive
        cd release
        tar -czf ${{ matrix.artifact_name }}.tar.gz ${{ matrix.artifact_name }}/
        
    - name: Copy binaries and create archive (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        # Copy binaries if they exist
        if [ -f "target/${{ matrix.target }}/release/goldbull-text.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-text.exe" release/${{ matrix.artifact_name }}/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-text-train.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-text-train.exe" release/${{ matrix.artifact_name }}/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-code.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-code.exe" release/${{ matrix.artifact_name }}/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-code-train.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-code-train.exe" release/${{ matrix.artifact_name }}/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-sage.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-sage.exe" release/${{ matrix.artifact_name }}/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-sage-train.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-sage-train.exe" release/${{ matrix.artifact_name }}/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-brief.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-brief.exe" release/${{ matrix.artifact_name }}/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-brief-train.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-brief-train.exe" release/${{ matrix.artifact_name }}/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-vision.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-vision.exe" release/${{ matrix.artifact_name }}/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-vision-train.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-vision-train.exe" release/${{ matrix.artifact_name }}/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-multimodel.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-multimodel.exe" release/${{ matrix.artifact_name }}/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-multimodel-train.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-multimodel-train.exe" release/${{ matrix.artifact_name }}/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-embedding.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-embedding.exe" release/${{ matrix.artifact_name }}/
        fi
        if [ -f "target/${{ matrix.target }}/release/goldbull-embedding-train.exe" ]; then
          cp "target/${{ matrix.target }}/release/goldbull-embedding-train.exe" release/${{ matrix.artifact_name }}/
        fi
        
        # Copy README and LICENSE if they exist
        if [ -f "README.md" ]; then
          cp README.md release/${{ matrix.artifact_name }}/
        fi
        if [ -f "LICENSE" ]; then
          cp LICENSE release/${{ matrix.artifact_name }}/
        fi
        
        # Create zip archive
        cd release
        7z a ${{ matrix.artifact_name }}.zip ${{ matrix.artifact_name }}/

    - name: Upload release asset (Unix)
      if: runner.os != 'Windows' && github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./release/${{ matrix.artifact_name }}.tar.gz
        asset_name: ${{ matrix.artifact_name }}.tar.gz
        asset_content_type: application/gzip

    - name: Upload release asset (Windows)
      if: runner.os == 'Windows' && github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./release/${{ matrix.artifact_name }}.zip
        asset_name: ${{ matrix.artifact_name }}.zip
        asset_content_type: application/zip

    - name: Upload build artifacts (Unix)
      if: always() && runner.os != 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}-release
        path: release/${{ matrix.artifact_name }}.tar.gz
        retention-days: 90

    - name: Upload build artifacts (Windows)
      if: always() && runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}-release
        path: release/${{ matrix.artifact_name }}.zip
        retention-days: 90